[versions]
agp = "8.8.0"
kotlin = "2.1.0"
rustAndroid = "0.9.6"
annotationJvm = "1.9.1"
coreKtx = "1.15.0"

[libraries]
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.1.10" }
android-library = { id = "com.android.library", version.ref = "agp" }
rust-android = { id = "org.mozilla.rust-android-gradle.rust-android", version.ref = "rustAndroid" }